# Generated by Django 4.2.4 on 2023-08-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Register',
        ),
    ]
