# Generated by Django 4.2.4 on 2023-08-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='group',
            new_name='groups',
        ),
    ]
